### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by webmasterkai** [OOKB/mgs2016#8]
```
program:
  label: display text.
  value: machine readable value
  alias: array used to map various google sheet values where needed.
  students: array of person references.

location:
  label: display text
  value: machine readable value
  alias: array used to map various google sheet values where needed.
  geoData: object that contains coordinate information.

person:
  name:
  bio:
  ...etc

art:
  creator: reference to person
  title:
  description:

ImageObject:
  art: reference to art entity.

showGroup:
  description: Just a simple description of the grouping used for administration. Allows grouping shows.

show:
  dateRange: single value date range
  showGroup: single value reference to a show group.
  programId: single value program reference.

showLocation:
  location: Single value location reference.
  students: multi-value person reference.
  show: single value show reference.
```
